import random
import nextcord
from nextcord.ext import commands


truth_responses = ["What is the most you’ve done for sex in the past?", "Who do you want to shower with?", "Do you want someone to pull my hair?", "What sexual adventures do you want to go on in 30 years?", "Have you ever wanted to be tied you up?", "Have you ever wanted me to tie you up?", "Have you ever given or received a lap dance?", "What’s the filthiest thing you’ve imagined doing to me?", "What is your wildest fantasy?", "What was the most powerful sexual experience you’ve ever had?", "When did you go solo for the first time?", "Have you ever been to a strip club?", "Do you have any interesting fetishes?", "When did you lose your virginity?", "What’s the most embarrassing thing that turns you on?", "Have you ever had a one-night stand?", "Have you ever considered a threesome?", "Have you ever gotten a bikini wax?", "How often do you trim down there?", "Would you be gay for £1000", "What's your body count", "", "How many people have seen you naked?", "Do you have any spicy pictures or videos saved on your phone?",
                   "Have you ever cheated?", "Have you ever made someone cry?", "What's your favorite place on your body to be kissed?", "if I went through your room, what would I be surprised to find?", "What was your first sexual experience?", "What was your wildest sexual experience?", "What is the dumbest thing I’ve ever said?", "When was your sexual awakening?", "What’s something your mom doesn’t know about you?", "What are you wearing?", "Have you ever searched for the cost of penis enlargement surgery?", "Do you wish to have double penertration?", "longest you've masturbated for?", "Longest you've had sex?", "Do you role-play? If so what kind of sexual role-play do you do??", "Can you deep throat?", "What's the maximum age diffrence that won't embarrass you in a relationship?", "What needs to be done to add variety to sexuality? Do you need variety now?", "Have you ever had a thought to by a sexy doll (women)?", "The weirdest place where you masturbated?", "Tell about your latest theft.", "Tell how perfect oral sex looks like for you."]
dares_responses = ["Remove two articles of clothing each round.", "Do your best version of the 'Single Ladies' dance and record it.", "Take off your clothes, but put on every piece of underwear that's in the house.", "Draw a picture of your partner and post it, saying how much you love them.", "Use provocative hand gestures every time you talk.", "Try to recreate a famous kissing scene from a movie", "Go to the fridge, pick out two different items, and use them to act out your favorite sexual act.", "Do the rest of the call naked, but wearing a winter jacket.", "Record and post a video of you holding your tongue and saying, “I am a very pretty hippopotamus.”", "Cut off a little bit of your hair", "Put your butt on the call and talk as it for one minute.", "One person gets to choose the other’s profile picture on Discord for the whole evening.", "Demonstrate your best sexual technique using your hands.", "Do a naked somersault.", "You have one minute to change into the hottest outfit you have.", "Go outside naked.", "Take off your pants", "Touch yourself every time you text.", "Write a 100-word naughty story and send it to them.", "Send the most unflattering picture of you that you have in your phone.", "Send them pictures of you trying to imitate five emojis that you pick out.",
                   "Go to the bathroom and make extremely loud grunting sounds. (Send audio, please.)", "Send the dirtiest text you can think of.", "Send a dirty message in emojis that the other person has to decode.", "Change your Discord status to “Feeling lonely . . .", "Feed someone almonds using just your mouth.", "Put on a dance song and grind with a pillow for one minute.", "Slap your butt and say, “I’ve been bad, bad, bad, bad, bad, bad, bad, bad, bad, naughty!”", "Put in your headphones and put on your favorite song and dance to it.", "Make out with your hand to “The Song That Never Ends” (look it up on YouTube).", "Demonstrate to the room how to put a condom on using a banana.", "Pick up a random book and read it in the most seductive voice you can manage.", "Pretend like you’re making sweet, sweet, love to the couch for one and a half minutes.", "Take off your shirt and pants, lay down on the ground, and act like a dolphin that’s gotten stranded on land for one minute.", "Cook two bags of popcorn. Eat all of it as fast as you can, but in the sexiest way possible.", "Make a orgasmic noise", "Try to hit on someone in this group like you’re at a bar.", "Use your butt to give a speech to the group about gas prices (or something else of your choosing).", "Do your best sexy crawl.", "Touch tongues with someone.", "Put someone else's underwear on your head", "Find an old photograph and recreate it as closely as possible.", "Let someone do whatever they want for two minutes with your phone.", "Say dirty words to the person closest.", "Use a sexy toy for 5 seconds.", "Share a embarrassing photo.", "Give a rim job with the person you're with.", "Caress your partners erogenic zones for 5 minutes", "Expand and eat the candy with your mouth only.", "Throw him/her on the bed and aactively kiss.", "Give an erotic compliment to your partner", "Touch the face, neck, belly, and groin with your nipples.", "Pin who you like to the wall and ferociously kiss him/her."]


class TruthorDare(commands.Cog):

    def __init__(self, client):
        self.client = client

    @commands.command(name="truth", description="Displays a truth you must answer")
    async def truth(self, ctx):
        await ctx.send(f"{random.choice(truth_responses)} {ctx.author.mention}")

    @commands.command(name="dare", description="Displays a truth you must answer")
    async def dare(self, ctx):
        await ctx.send(f"{random.choice(dares_responses)} {ctx.author.mention}")
